name: CICD_lesson_pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23.9
    steps:
      - uses: actions/checkout@v4

      - name: Vet
        run: |
          go vet ./...

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test